const globals = require('globals');

module.exports = [
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.commonjs,
        jQuery: 'readonly',
        $: 'readonly',
      },
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: 'module',
      },
    },
    rules: {
      // Espaçamento e formatação
      'no-irregular-whitespace': ['error', { skipComments: true }],
      'array-bracket-spacing': ['error', 'never'],
      'block-spacing': ['error', 'always'],
      'brace-style': ['error', '1tbs', { allowSingleLine: true }],
      'comma-spacing': ['error', { after: true, before: false }],
      'comma-style': ['error', 'last'],
      'computed-property-spacing': 'off',
      'indent': ['error', 2],
      'key-spacing': 'off',
      'keyword-spacing': ['error', { after: true, before: true }],
      'linebreak-style': 'off',
      'no-multi-spaces': 'off',
      'no-multiple-empty-lines': 'error',
      'no-trailing-spaces': 'error',
      'object-curly-spacing': ['error', 'always'],
      'space-before-blocks': 'error',
      'space-before-function-paren': 'off',
      'space-in-parens': 'off',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'spaced-comment': ['error', 'always'],
      'template-curly-spacing': 'error',

      // Estilo de código
      'quotes': ['error', 'single'],
      'semi': ['error', 'always'],
      'semi-spacing': 'error',
      'arrow-body-style': 'error',
      'arrow-parens': 'error',
      'arrow-spacing': 'error',
      'func-style': ['error', 'expression'],
      'generator-star-spacing': 'error',
      'yield-star-spacing': 'error',
      'prefer-const': 'error',
      'prefer-spread': 'error',
      'no-var': 'off',
      'object-shorthand': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-template': 'off',
      'quote-props': 'off',

      // Variáveis e declarações
      'block-scoped-var': 'error',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-use-before-define': 'error',
      'vars-on-top': 'off',
      'one-var': 'off',
      'one-var-declaration-per-line': 'error',
      'sort-vars': 'error',

      // Funções
      'func-names': 'off',
      'max-params': ['error', 4],
      'no-empty-function': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-invalid-this': 'off',
      'no-return-assign': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'prefer-rest-params': 'off',
      'require-yield': 'error',

      // Objetos e arrays
      'no-array-constructor': 'error',
      'no-new-object': 'error',
      'no-new-wrappers': 'error',

      // Controle de fluxo
      'curly': 'error',
      'default-case': 'error',
      'no-else-return': 'error',
      'no-lonely-if': 'error',
      'no-nested-ternary': 'off',
      'no-ternary': 'off',
      'no-unneeded-ternary': 'error',

      // Loops
      'no-continue': 'error',
      'no-loop-func': 'error',
      'no-unmodified-loop-condition': 'error',

      // Operadores
      'dot-location': ['error', 'property'],
      'dot-notation': 'error',
      'no-floating-decimal': 'error',
      'no-plusplus': 'off',
      'operator-assignment': ['error', 'always'],
      'operator-linebreak': 'off',
      'radix': 'error',
      'yoda': ['error', 'never'],

      // Comparações
      'eqeqeq': 'off',
      'no-eq-null': 'error',
      'no-self-compare': 'error',

      // Tipos
      'valid-typeof': 'error',

      // Erros comuns
      'no-alert': 'error',
      'no-caller': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-label-var': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-proto': 'error',
      'no-script-url': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-void': 'error',
      'no-with': 'error',

      // Boas práticas
      'accessor-pairs': 'error',
      'array-callback-return': 'error',
      'complexity': 'error',
      'consistent-return': 'off',
      'consistent-this': 'off',
      'guard-for-in': 'error',
      'max-depth': 'error',
      'max-nested-callbacks': 'error',
      'max-statements': 'off',
      'no-bitwise': 'off',
      'no-catch-shadow': 'error',
      'no-confusing-arrow': 'error',
      'no-div-regex': 'error',
      'no-implicit-globals': 'error',
      'no-inner-declarations': ['error', 'functions'],
      'no-lone-blocks': 'error',
      'no-magic-numbers': 'off',
      'no-multi-str': 'error',
      'no-new-require': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'off',
      'no-path-concat': 'error',
      'no-process-env': 'error',
      'no-process-exit': 'error',
      'no-restricted-globals': 'error',
      'no-restricted-imports': 'error',
      'no-restricted-syntax': 'error',
      'no-unused-expressions': 'off',
      'no-warning-comments': 'error',
      'no-whitespace-before-property': 'error',
      'prefer-reflect': 'off',
      'wrap-iife': 'error',
      'wrap-regex': 'off',

      // Comentários e documentação
      'no-inline-comments': 'off',
      'lines-around-comment': 'off',
      'require-jsdoc': 'off',
      'valid-jsdoc': 'off',

      // Outros
      'callback-return': 'error',
      'camelcase': 'error',
      'eol-last': 'off',
      'global-require': 'off',
      'handle-callback-err': 'error',
      'id-blacklist': 'error',
      'id-length': 'off',
      'id-match': 'error',
      'init-declarations': 'error',
      'jsx-quotes': 'error',
      'max-len': 'off',
      'new-cap': 'error',
      'new-parens': 'error',
      'newline-after-var': 'off',
      'newline-before-return': 'off',
      'newline-per-chained-call': 'off',
      'no-cond-assign': ['error', 'except-parens'],
      'no-extra-parens': 'off',
      'no-mixed-requires': 'error',
      'no-native-reassign': 'error',
      'no-negated-condition': 'off',
      'no-restricted-modules': 'error',
      'no-sync': 'error',
      'padded-blocks': 'off',
      'strict': 'off',
    },
  },
];
